### ISSUE TITLE
Oracle Socket error

### ISSUE THREAD

**Issue by valdasraps** [valdasraps/resthub#4]
Caused by: org.hibernate.TransactionException: unable to commit against JDBC connection
        at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.doCommit(JdbcTransaction.java:116)
        at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:178)
        ... 55 more
Caused by: java.sql.SQLRecoverableException: No more data to read from socket
        at oracle.jdbc.driver.T4CMAREngine.unmarshalUB1(T4CMAREngine.java:1157)
        at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:290)
        at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:192)
        at oracle.jdbc.driver.T4C7Ocommoncall.doOCOMMIT(T4C7Ocommoncall.java:75)
        at oracle.jdbc.driver.T4CConnection.doCommit(T4CConnection.java:610)
        at oracle.jdbc.driver.PhysicalConnection.commit(PhysicalConnection.java:3901)
        at oracle.jdbc.driver.PhysicalConnection.commit(PhysicalConnection.java:3907)
        at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.doCommit(JdbcTransaction.java:112)

**Comment by valdasraps** [comment]
database problem
