### ISSUE TITLE
GROUP BY seems broken (at least in the python client)

### ISSUE THREAD

**Issue by SenneVanPutte** [valdasraps/resthub#46]
I was trying to get grouped data from the trkr_shipment_stats_v (since there is no shipments table directly).
But any query that I formulate with a GROUP BY statement seems to fail.
e.g.:
```sql
SELECT s.shipment_id,s.status FROM trker_cmsr.trkr_shipment_stats_v s GROUP BY s.shipment_id
```
The resulting error is always:
```
Exception: Response (500): The server encountered an unexpected condition which prevented it from fulfilling the request
```
Which is not very descriptive. The python stack trace is:
```
Traceback (most recent call last):
  File "/my/path/rhapi.py", line 799, in run
    data = method(arg, params=params, pagesize=options.size, page=options.page,
  File "/my/path/rhapi.py", line 496, in json2
    qid = self.qid(query)
  File "/my/path/rhapi.py", line 390, in qid
    return self.get(["query"], query)
  File "/my/path/rhapi.py", line 328, in get
    raise Exception('Response (' + str(resp.status_code) + '): ' + resp.text)
```
So it seems to fail to build the query properly

**Comment by SenneVanPutte** [comment]
My mistake, the SQL syntax was incorrect, it should have been:
```sql
SELECT s.shipment_id,s.status FROM trker_cmsr.trkr_shipment_stats_v s GROUP BY s.shipment_id,s.status
```
adding `,s.status` at the end as the status info is not bound to the `shipment_id`.
Please feel free to remove the issue.
